/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ImageExport { 'imageData' : Uint8Array, 'imageId' : string }
export interface Nakshatra {
  'karmicLesson' : string,
  'rulingDeity' : string,
  'name' : string,
  'description' : string,
  'lunarClimate' : string,
  'pada1' : PadaInfo,
  'pada2' : PadaInfo,
  'pada3' : PadaInfo,
  'pada4' : PadaInfo,
  'imageId' : [] | [string],
  'characteristics' : string,
  'symbol' : string,
}
export interface PadaInfo { 'title' : string, 'description' : string }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createNakshatra' : ActorMethod<[Nakshatra], boolean>,
  'deleteImage' : ActorMethod<[string], boolean>,
  'deleteNakshatra' : ActorMethod<[string], boolean>,
  'exportImageData' : ActorMethod<[], Array<ImageExport>>,
  'exportNakshatraData' : ActorMethod<[], Array<Nakshatra>>,
  'getAllNakshatras' : ActorMethod<[], Array<Nakshatra>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getImage' : ActorMethod<[string], [] | [Uint8Array]>,
  'getNakshatraByNumber' : ActorMethod<[bigint], [] | [Nakshatra]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'importImageData' : ActorMethod<[Array<ImageExport>], undefined>,
  'importNakshatraData' : ActorMethod<[Array<Nakshatra>], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'readNakshatra' : ActorMethod<[string], [] | [Nakshatra]>,
  'replaceNakshatraImage' : ActorMethod<[string, Uint8Array], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchNakshatras' : ActorMethod<[string], Array<Nakshatra>>,
  'updateNakshatra' : ActorMethod<[Nakshatra], boolean>,
  'uploadImage' : ActorMethod<[Uint8Array], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];