/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Nakshatra = IDL.Record({
  'rulingDeity' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'characteristics' : IDL.Text,
  'symbol' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'createNakshatra' : IDL.Func([Nakshatra], [IDL.Bool], []),
  'deleteNakshatra' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllNakshatras' : IDL.Func([], [IDL.Vec(Nakshatra)], ['query']),
  'getNakshatraByNumber' : IDL.Func([IDL.Nat], [IDL.Opt(Nakshatra)], ['query']),
  'initialize' : IDL.Func([], [], []),
  'readNakshatra' : IDL.Func([IDL.Text], [IDL.Opt(Nakshatra)], ['query']),
  'searchNakshatras' : IDL.Func([IDL.Text], [IDL.Vec(Nakshatra)], ['query']),
  'updateNakshatra' : IDL.Func([Nakshatra], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Nakshatra = IDL.Record({
    'rulingDeity' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'characteristics' : IDL.Text,
    'symbol' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'createNakshatra' : IDL.Func([Nakshatra], [IDL.Bool], []),
    'deleteNakshatra' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllNakshatras' : IDL.Func([], [IDL.Vec(Nakshatra)], ['query']),
    'getNakshatraByNumber' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(Nakshatra)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'readNakshatra' : IDL.Func([IDL.Text], [IDL.Opt(Nakshatra)], ['query']),
    'searchNakshatras' : IDL.Func([IDL.Text], [IDL.Vec(Nakshatra)], ['query']),
    'updateNakshatra' : IDL.Func([Nakshatra], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };