/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PadaInfo = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const Nakshatra = IDL.Record({
  'karmicLesson' : IDL.Text,
  'rulingDeity' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'lunarClimate' : IDL.Text,
  'pada1' : PadaInfo,
  'pada2' : PadaInfo,
  'pada3' : PadaInfo,
  'pada4' : PadaInfo,
  'imageId' : IDL.Opt(IDL.Text),
  'characteristics' : IDL.Text,
  'symbol' : IDL.Text,
});
export const ImageExport = IDL.Record({
  'imageData' : IDL.Vec(IDL.Nat8),
  'imageId' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createNakshatra' : IDL.Func([Nakshatra], [IDL.Bool], []),
  'deleteImage' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteNakshatra' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'exportImageData' : IDL.Func([], [IDL.Vec(ImageExport)], ['query']),
  'exportNakshatraData' : IDL.Func([], [IDL.Vec(Nakshatra)], ['query']),
  'getAllNakshatras' : IDL.Func([], [IDL.Vec(Nakshatra)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getImage' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Vec(IDL.Nat8))], ['query']),
  'getNakshatraByNumber' : IDL.Func([IDL.Nat], [IDL.Opt(Nakshatra)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'importImageData' : IDL.Func([IDL.Vec(ImageExport)], [], []),
  'importNakshatraData' : IDL.Func([IDL.Vec(Nakshatra)], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'readNakshatra' : IDL.Func([IDL.Text], [IDL.Opt(Nakshatra)], ['query']),
  'replaceNakshatraImage' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat8)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchNakshatras' : IDL.Func([IDL.Text], [IDL.Vec(Nakshatra)], ['query']),
  'updateNakshatra' : IDL.Func([Nakshatra], [IDL.Bool], []),
  'uploadImage' : IDL.Func([IDL.Vec(IDL.Nat8)], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PadaInfo = IDL.Record({ 'title' : IDL.Text, 'description' : IDL.Text });
  const Nakshatra = IDL.Record({
    'karmicLesson' : IDL.Text,
    'rulingDeity' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'lunarClimate' : IDL.Text,
    'pada1' : PadaInfo,
    'pada2' : PadaInfo,
    'pada3' : PadaInfo,
    'pada4' : PadaInfo,
    'imageId' : IDL.Opt(IDL.Text),
    'characteristics' : IDL.Text,
    'symbol' : IDL.Text,
  });
  const ImageExport = IDL.Record({
    'imageData' : IDL.Vec(IDL.Nat8),
    'imageId' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createNakshatra' : IDL.Func([Nakshatra], [IDL.Bool], []),
    'deleteImage' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteNakshatra' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'exportImageData' : IDL.Func([], [IDL.Vec(ImageExport)], ['query']),
    'exportNakshatraData' : IDL.Func([], [IDL.Vec(Nakshatra)], ['query']),
    'getAllNakshatras' : IDL.Func([], [IDL.Vec(Nakshatra)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getImage' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Vec(IDL.Nat8))], ['query']),
    'getNakshatraByNumber' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(Nakshatra)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'importImageData' : IDL.Func([IDL.Vec(ImageExport)], [], []),
    'importNakshatraData' : IDL.Func([IDL.Vec(Nakshatra)], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'readNakshatra' : IDL.Func([IDL.Text], [IDL.Opt(Nakshatra)], ['query']),
    'replaceNakshatraImage' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat8)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchNakshatras' : IDL.Func([IDL.Text], [IDL.Vec(Nakshatra)], ['query']),
    'updateNakshatra' : IDL.Func([Nakshatra], [IDL.Bool], []),
    'uploadImage' : IDL.Func([IDL.Vec(IDL.Nat8)], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };